### ISSUE TITLE
URIError: Failed to decode param

### ISSUE THREAD

**Issue by mythmakerseven** [mythmakerseven/octagon-moon#7]
Just saw this in the logs:

```
[octagon-moon] [2021-11-10 09:18:19] URIError: Failed to decode param '99%'
[octagon-moon] [2021-11-10 09:18:19]     at decodeURIComponent (<anonymous>)
[octagon-moon] [2021-11-10 09:18:19]     at decode_param (/workspace/node_modules/express/lib/router/layer.js:172:12)
[octagon-moon] [2021-11-10 09:18:19]     at Layer.match (/workspace/node_modules/express/lib/router/layer.js:148:15)
[octagon-moon] [2021-11-10 09:18:19]     at matchLayer (/workspace/node_modules/express/lib/router/index.js:574:18)
[octagon-moon] [2021-11-10 09:18:19]     at next (/workspace/node_modules/express/lib/router/index.js:220:15)
[octagon-moon] [2021-11-10 09:18:19]     at Function.handle (/workspace/node_modules/express/lib/router/index.js:174:3)
[octagon-moon] [2021-11-10 09:18:19]     at router (/workspace/node_modules/express/lib/router/index.js:47:12)
[octagon-moon] [2021-11-10 09:18:19]     at Layer.handle [as handle_request] (/workspace/node_modules/express/lib/router/layer.js:95:5)
[octagon-moon] [2021-11-10 09:18:19]     at trim_prefix (/workspace/node_modules/express/lib/router/index.js:317:13)
[octagon-moon] [2021-11-10 09:18:19]     at /workspace/node_modules/express/lib/router/index.js:284:7
```

Someone searched for "99%" and the % sign broke the search. This *should* be handled by the regex sanitizer but apparently not! Will look into it later.

**Comment by mythmakerseven** [comment]
Fixed with https://github.com/mythmakerseven/octagon-moon/commit/a702b8c25149fba98329040b4fbba65b6c47ed90
